import "../css/Features.css";

function Features() {
  return (
    <section className="features">
      <div className="section-title">
        <h2>Why Choose PrepAI?</h2>
        <p>Everything you need to practice and improve your interview skills.</p>
      </div>

      <div className="feature-grid">
        <div className="feature-card">
          <h3>🤖 AI Questions</h3>
          <p>Get role-based interview questions generated by AI.</p>
        </div>

        <div className="feature-card">
          <h3>📝 MCQ Tests</h3>
          <p>Practice technical MCQs with instant answer checking.</p>
        </div>

        <div className="feature-card">
          <h3>💬 AI Feedback</h3>
          <p>Receive smart feedback and improve your answers.</p>
        </div>

        <div className="feature-card">
          <h3>📊 Progress Tracking</h3>
          <p>Track your scores, weak topics, and interview history.</p>
        </div>
      </div>
    </section>
  );
}

export default Features;